### ISSUE TITLE
matchtimeseries in stations application.wadl

### ISSUE THREAD

**Issue by krischer** [INGV/FDSN-WS#1]
The `application.wadl` file of the `station` service contains the `matchtimeseries` parameter:

http://webservices.rm.ingv.it/fdsnws/station/1/application.wadl

This means that queries such as 

http://webservices.rm.ingv.it/fdsnws/station/1/query?format=text&level=channel&longitude=12.4754858017&latitude=43.7210845947&starttime=2015-08-21T17:09:31.100000&matchtimeseries=true&endtime=2015-08-21T18:14:31.100000&maxradius=14.1421356237&minradius=0.0

do not work.

The WADL files specifies that the parameter is not yet implemented in its documentation which I (as a human) can tell. The purpose of WADL files is to provide machine readable information about what a service is capable of. Thus your current `application.wadl` file breaks automatic tools relying on that information. An example of this is the [ObsPy mass downloader](https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.mass_downloader.html) which currently does not work with INGV.

Please remove all not implemented parameters from the WADL file until they are implemented. The currently not implemented parameters are also not standard parameters according to the spec so there is no harm in removing them.

**Comment by krischer** [comment]
Just a quick reminder that this is still not fixed and breaks compatibility with ObsPy.

**Comment by krischer** [comment]
My bi-weekly reminder that this still does not work ;-)

**Comment by petrrr** [comment]
Should be fixed now. 
Thanks @matteoquintiliani!

**Comment by krischer** [comment]
Thanks a lot!
